spring:
  datasource:
    # configure a JDBC connection
    username: demo
    password: 'demo'
    #applied mysql version：Server version: 5.6.11 MySQL Community Server (GPL)
    #mysql Driver version：mysql-connector-java-8.0.16.jar
    #Starting from version 8.0, the MySQL JDBC driver has been updated and the
    #driver class name has changed from com.mysql.jdbc.Driver to com.mysql.cj.jdbc.Driver.
    url: jdbc:mysql://127.0.0.1:3306/student_system?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# mybatis_plus configuration
mybatis_plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl